language: python
python:
- '3.4'
- '3.5'
- '3.6'
- '3.7'
- '3.8'
install: pip install -r requirements.txt && pip install pylint
sudo: false
script: make test
notifications:
  email: false
  slack:
    secure: wjQ+Ry4VqkTnplDAeZG5hO/3ciqaZf3Hb7Bg/awwlCkyeELujWgkB1eFkcqBQyuejNzPKjPYqL3yBXnyeoHL5YIri+uq1fnnggCCoQGrwBGnWYaBlugZIV8EjpaBSUkmvL+6SnTMZZ0caYajObynPUc4NrZ1Wiuho8i+mcZbfx/2Lv1zWRLKQavx28sWQBkGY2bu7olvPGsiEOQ8n8HPKAhsgBB6noPicE/lgELexabDBG21gSm3iBR2nIbgAuauWpg5qwWrpqc/bMIGekhr1bTvHwm0KxeNU3dkTaAFP+6inhqhclJo1rG7s0Z3yukRNNA4w7kGBxSEvEeYeOQrvXtIjV3HYua4uxcxz8gmTbwrOGvbOi+xiQG18MEadsx1VYFIudWdjQgCLEp5x6eCo2RB43wwfVHgzMxcUBvKGlgtz023y2T4xoh6Hpm4YxO059pJiGUKY1yedjF494F5mzlcbLYaIiuzsQ8eivgDS21sGADAamz8KMgzMjKMaSZmomOmL7EQkgIYww1G2rQ2uR+vOwqAyx96rCyH2PMfFjzR3ZoOxASN4S/bNhXEkvWX1g9JI4kLXEaG9U4uzcBdJOki464oH1ZSKeYc0mM3JNrXwvb9CXhrNuLw7xQ9bImYW1wIhH/ivQqxUNw5YD98t/QZgAJ+84TdHMX1qiz4akQ=
